//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface INotificationItem
{
	notificationId: string;
	type: string;
	title: string;
	message: string;
	timestamp: string;
	isRead: boolean;
	actionUrl: string;
}
