//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ICalcRaffleOrderStatisticsResult
{
	soldOrderCount: number;
	soldTicketCount: number;
	totalSoldAmount: number;
	checkedOrderCount: number;
	checkedSoldAmount: number;
	buyerCount: number;
}
