@AuctionHouseApp.Server_HostAddress = https://localhost:60026

### 2.x 貴賓名冊
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/guestlist
Accept: application/json
Content-Type: application/json

{
	"credential": "AIzaSyDaGmWKa4JsXZ-HjGw7ISLn_3namBGewQe"
}

### 2.1 賓客登入 (取得 Token)
# @name loginRequest
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/login
Accept: application/json
Content-Type: application/json

{
	"name": "Arnold Alois Schwarzenegger"
}

### 2.1 賓客登入 (取得 Token)
# @name loginRequest
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/login
Accept: application/json
Content-Type: application/json

{
	"name": "Alois"
}

### 2.1 賓客登入 (有多位符合)
# @name loginRequest
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/login
Accept: application/json
Content-Type: application/json

{
	"name": "a"
}

### 通訊測試 (需攜帶 Token)
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/authstatus
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試：測試有 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試：測試無 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json

### 通訊測試：測試給錯的 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
Authorization: Bearer abcdefghijklmnopqrstuvwxyz

###------------------------------------
### 3.1 取得所有活動狀態
GET {{AuctionHouseApp.Server_HostAddress}}/api/activities/status
Accept: application/json

### 4.1 大螢幕狀態查詢
GET {{AuctionHouseApp.Server_HostAddress}}/api/display/status
Accept: application/json

###------------------------------------

### 5.1 取得獎品清單
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/prizes
Accept: application/json

### 5.2 取得指定獎品詳情
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/prizes/R03
Accept: application/json

### 5.2 取得指定獎品詳情 (錯誤商品ID)
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/prizes/xxx
Accept: application/json

### 5.3 取得我的票券 [須先登入認證]
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/mytickets
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 5.4 取得中獎結果 (大螢幕觸發抽三獎→二獎→一獎)
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/winner/R03
Accept: application/json

### 5.5 取得所有得獎名單 (大螢幕)
GET {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/winners
Accept: application/json

### 5.x 一口氣抽完小獎（三大獎外）
POST {{AuctionHouseApp.Server_HostAddress}}/api/raffleticket/DrawMinorWinners
Accept: application/json

###------------------------------------
### 6.1 取得福袋清單
GET {{AuctionHouseApp.Server_HostAddress}}/api/givetowin/gifts
Accept: application/json

### 指定測試參數
@GiftId = G01

### 6.2 取得單一福袋詳情
GET {{AuctionHouseApp.Server_HostAddress}}/api/givetowin/gifts/{{GiftId}}
Accept: application/json

### 6.3 取得我的福袋(抽獎券) [須先登入認證]
GET {{AuctionHouseApp.Server_HostAddress}}/api/givetowin/mytickets/{{GiftId}}
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 6.4 取得福袋中獎結果(大螢幕)
GET {{AuctionHouseApp.Server_HostAddress}}/api/givetowin/result/{{GiftId}}

###------------------------------------
### 7.1 取得拍賣商品預覽
GET {{AuctionHouseApp.Server_HostAddress}}/api/liveauction/preview
Accept: application/json

### 7.2 取得指定拍賣商品詳情
GET {{AuctionHouseApp.Server_HostAddress}}/api/liveauction/preview/L02
Accept: application/json

### 7.2 取得指定拍賣商品詳情 (錯誤商品ID)
GET {{AuctionHouseApp.Server_HostAddress}}/api/liveauction/preview/xxx
Accept: application/json

###------------------------------------
### 8.1 取得商品清單
GET {{AuctionHouseApp.Server_HostAddress}}/api/silentauction/items
Accept: application/json

### 8.2 取得單一商品詳情
GET {{AuctionHouseApp.Server_HostAddress}}/api/silentauction/items/S01
Accept: application/json

### 8.2 取得單一商品詳情 (錯誤商品ID)
GET {{AuctionHouseApp.Server_HostAddress}}/api/silentauction/items/xxx
Accept: application/json

### 8.x 取前端網址
GET {{AuctionHouseApp.Server_HostAddress}}/api/silentauction/fronturlbase
Accept: application/json

###------------------------------------

