@AuctionHouseApp.Server_HostAddress = https://localhost:60026

### VIP登入測試 (取得 Token)
# @name loginRequest
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/login
Accept: application/json
Content-Type: application/json

{
	"name": "smart",
	"email": "smart@mail.server"
}

### 通訊測試 (需攜帶 Token)
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/authstatus
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試 (需攜帶 Token)
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試 (無 Token)
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
