@AuctionHouseApp.Server_HostAddress = https://localhost:60026

### 2.1 賓客登入 (取得 Token)
# @name loginRequest
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/login
Accept: application/json
Content-Type: application/json

{
	"name": "Arnold Alois Schwarzenegger",
	"email": "arnold@mail.server"
}

### 通訊測試 (需攜帶 Token)
POST {{AuctionHouseApp.Server_HostAddress}}/api/auth/vip/authstatus
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試：測試有 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
Authorization: Bearer {{loginRequest.response.body.$.data.token}}

### 通訊測試：測試無 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json

### 通訊測試：測試給錯的 Token
POST {{AuctionHouseApp.Server_HostAddress}}/api/WeatherForecast/QryDataList
Accept: application/json
Authorization: Bearer abcdefghijklmnopqrstuvwxyz

###------------------------------------
### 3.1 取得所有活動狀態
GET {{AuctionHouseApp.Server_HostAddress}}/api/activities/status
Accept: application/json

### 4.1 大螢幕狀態查詢
GET {{AuctionHouseApp.Server_HostAddress}}/api/display/status
Accept: application/json

###------------------------------------

### 7.1 取得拍賣商品預覽
GET {{AuctionHouseApp.Server_HostAddress}}/api/liveauction/preview
Accept: application/json

### 7.2 取得指定拍賣商品詳情
GET {{AuctionHouseApp.Server_HostAddress}}/api/liveauction/preview/L02
Accept: application/json
