//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IOpenAskRecord
{
	ssn: number;
	round: number;
	paddleNum: string;
	paddleName: string;
	amount: number;
	recordStaff1: string;
	recordDtm1: any;
	recordStaff2: string;
	recordDtm2: any;
	status: string;
	hasPaid: string;
	paidDtm: any;
	paidStaff: string;
	hasFix: string;
	fixStaff: string;
	fixDtm: any;
	fixRemark: string;
}
