//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IRaffleTicket
{
	raffleTicketNo: string;
	raffleSoldNo: string;
	buyerName: string;
	buyerEmail: string;
	buyerPhone: string;
	emailTimes: number;
	lastEmailDtm: any;
	Copy(src: IRaffleTicket) : void;
	Clone() : IRaffleTicket;
}
