//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISilentPrize
{
	itemId: string;
	name: string;
	description: string;
	image: string;
	startPrice: number;
	minIncrement: number;
	startTime: string;
	endTime: string;
	status: string;
	displayOrder: number;
	createdAt: any;
	updatedAt: any;
	createdBy: string;
}
