//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISilentAuctionItem
{
	itemId: string;
	name: string;
	description: string;
	image: string;
	startPrice: number;
	currentPrice: number;
	minIncrement: number;
	currentBidderPaddleNum: string;
	currentBidderPaddleName: string;
	endTime: string;
}
