//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ISilentAuctionPrivateBidHistoryItem } from './ISilentAuctionPrivateBidHistoryItem';

export interface ISilentAuctionBidHistoryDetail
{
	itemId: string;
	currentPrice: number;
	isCurrentBidder: boolean;
	bidHistory: ISilentAuctionPrivateBidHistoryItem[];
	userCurrentBid: number;
}
