//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ISilentAuctionManualHammerItem } from './ISilentAuctionManualHammerItem';

export interface ISilentAuctionManualHammerResponse
{
	hammeredCount: number;
	passedCount: number;
	totalCount: number;
	items: ISilentAuctionManualHammerItem[];
}
