//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISilentAuctionBidResponse
{
	itemId: string;
	amount: number;
	isHighestBid: boolean;
	currentHighestBid: number;
	timestamp: string;
}
