//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IRaffleWinnerItem
{
	prizeId: string;
	prizeName: string;
	prizeDescription: string;
	prizeImage: string;
	prizeValue: string;
	winnerID: string;
	winnerName: string;
	ticketNumber: string;
	drawTime: string;
}
