//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IBatchPaymentItem } from './IBatchPaymentItem';

export interface IBatchUpdatePaymentArgs
{
	paddleNum: string;
	transactions: IBatchPaymentItem[];
	paymentStatus: string;
	paymentNotes: string;
}
