//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ITransactionItem
{
	transactionId: string;
	type: string;
	name: string;
	amount: number;
	status: string;
	paidAmount: number;
	time: string;
}
