//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ITransactionWinningTickets } from './ITransactionWinningTickets';
import { ITransactionSummary } from './ITransactionSummary';
import { ITransactionItem } from './ITransactionItem';
import { IReceiptInfo } from './IReceiptInfo';

export interface ITransactionSummaryResult_Data
{
	winningTickets: ITransactionWinningTickets;
	summary: ITransactionSummary;
	transactions: ITransactionItem[];
	receiptInfo: IReceiptInfo;
}
