//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IUpdatePaymentArgs
{
	paddleNum: string;
	type: string;
	transactionId: string;
	paymentStatus: string;
	paidAmount: number;
	paymentNotes: string;
}
