//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ILiveAuctionStatus
{
	currentPrice: number;
	bidderID: string;
	bidderName: string;
	timestamp: string;
	isEnded: boolean;
	finalWinnerID: string;
	finalWinnerName: string;
}
