//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IAuthVipLoginResult_Guest
{
	id: string;
	name: string;
	email: string;
	tableNumber: string;
}
