//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IAuthVipLoginResult_Data } from './IAuthVipLoginResult_Data';

export interface IAuthVipLoginResult
{
	success: boolean;
	data: IAuthVipLoginResult_Data;
	message: string;
}
