//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IAuthVipLoginResult_Guest } from './IAuthVipLoginResult_Guest';

export interface IAuthVipLoginResult_Data
{
	token: string;
	guest: IAuthVipLoginResult_Guest;
}
