//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IStaffAccount
{
	userId: string;
	nickname: string;
	phone: string;
	roleList: string[];
	expiresTime: string;
	status: string;
}
